name: placar_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0
  firebase_database: ^10.3.4
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_backgorund: "#FFFFFF"
  adaptive_icon_foreground: "assets/imagens/padrao.png"
  ios: true  
  remove_alpha_ios: true
  image_path: "assets/imagens/loguinho.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/imagens/padrao.png
    - assets/imagens/placar.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fontes/Montserrat-Regular.ttf
        - asset: assets/fontes/Montserrat-Bold.ttf
        - asset: assets/fontes/Montserrat-ExtraLight.ttf
